import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"], // elegí los pesos que quieras
  variable: "--font-roboto-condensed", // opcional para usar como CSS variable
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // elegí los pesos que quieras
  variable: "--font-roboto", // opcional para usar como CSS variable
});

export const metadata: Metadata = {
  title: "Panal de letras",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
